#!/bin/bash

arg=$1

echo $arg

if [ "$arg" == "up" ];
then
cd server; docker-compose --file docker-compose.yml up --detach; cd -
fi

if [ "$arg" == "down" ];
then
cd server; docker-compose down --remove-orphans; cd -
fi
